quarkus:

  datasource:
    password: local
    username: local_user
    jdbc:
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/calendar_alexa
    db-kind: postgresql

  http:
    port: ${PORT:8080}
    auth:
      basic: true

  hibernate-orm:
    database:
      generation: none

  live-reload:
    instrumentation: true

  rest-client:
    oauth2-google:
      url: https://oauth2.googleapis.com

  cache:
    caffeine:
      "oauth-token-cache":
        expire-after-write: 3599S

  flyway:
    baseline-on-migrate: true
    migrate-at-start: false
    locations: filesystem:src/main/resources/db/migration
